---
- name: Install Python
  apt: name={{ item }} update_cache=yes state=installed
  with_items:
    - git
    - python3
    - python3-pip
    - python3-dev
    - build-essential
    - libssl-dev
    - libffi-dev
    - python3-setuptools
    - python3-venv
